In [1]:
import numpy as np
a=np.array([1,2,3])
a

array([1, 2, 3])

In [2]:
b=np.array([1,2],[3,4])
b

TypeError: data type not understood

In [3]:
b=np.array(([1,2],[3,4])
b

SyntaxError: invalid syntax (<ipython-input-3-ed4356548553>, line 2)

In [4]:
b=np.array(([1,2],[3,4]))
b

array([[1, 2],
       [3, 4]])

In [5]:
a=np.array(([1,2,3],[4,5,6]))
a


array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
a=np.array(([1,2,3],[4,5,6]))
a
a.shape


(2, 3)

In [7]:
b=a.reshape(3,2)
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [8]:
np.random.rand(5)

array([0.14440103, 0.80801609, 0.32952569, 0.04063175, 0.25067318])

In [9]:
np.random.rand(5)

array([0.57097555, 0.96435806, 0.50598498, 0.87327557, 0.54029263])

In [10]:
np.random.randn(2)

array([-0.70413254, -0.2446215 ])

In [11]:
np.random.randint(1,100)

87

In [2]:
import numpy as np
a=np.array([[1,2],[3,4]])

b=np.array([[5,6],[7,8]])

np.concatenate(a,b)


TypeError: only integer scalar arrays can be converted to a scalar index

In [3]:
import numpy as np
a=np.array([[1,2],[3,4]])

b=np.array([[5,6],[7,8]])

np.concatenate(a,b)


TypeError: only integer scalar arrays can be converted to a scalar index

In [4]:
import numpy as np
a=np.array([[1,2],[3,4]])


In [5]:
import numpy as np
a=np.array([[1,2],[3,4]])

b=np.array([[5,6],[7,8]])

np.concatenate((a,b))



array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [6]:
np.concatenate((a,b),axis=1)


array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [7]:
a=np.array([[1,2,3],[4,5,6]])
a


array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
np.append(a,[7,8,9])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.append(a,[7,8,9],axis=0)

ValueError: all the input arrays must have same number of dimensions

In [10]:
np.append(a,[[7,8,9]],axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
np.append(a,[[7,8,9]],axis=1)

ValueError: all the input array dimensions except for the concatenation axis must match exactly

In [12]:
np.append(a,[[5,5,5][7,8,9]],axis=1)

TypeError: list indices must be integers or slices, not tuple

In [13]:
np.append(a,[[5,5,5],[7,8,9]],axis=1)

array([[1, 2, 3, 5, 5, 5],
       [4, 5, 6, 7, 8, 9]])

In [14]:
a=np.array([[3,7,5],[8,4,3],[2,4,9]])
a

array([[3, 7, 5],
       [8, 4, 3],
       [2, 4, 9]])

In [15]:
np.amin(a)

2

In [16]:
np.amin(a,axis=0)

array([2, 4, 3])

In [17]:
np.amin(a,axis=1)

array([3, 3, 2])

In [18]:
np.amax(a)

9

In [19]:
np.amax(a,axis=0)

array([8, 7, 9])

In [20]:
np.amax(a,axis=1)

array([7, 8, 9])

In [21]:
a=np.array([[1,2],[3,4],[5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [22]:
np.insert(a,3,[11,12])

array([ 1,  2,  3, 11, 12,  4,  5,  6])

In [23]:
np.insert(a,1,[11,12],axis=0)

array([[ 1,  2],
       [11, 12],
       [ 3,  4],
       [ 5,  6]])

In [24]:
np.insert(a,1,[11,12,13],axis=0)

ValueError: could not broadcast input array from shape (1,3) into shape (1,2)

In [25]:
np.insert(a,1,[11,12,13],axis=1)

array([[ 1, 11,  2],
       [ 3, 12,  4],
       [ 5, 13,  6]])

In [ ]:
import pandas as pd
import numpy as np
data=np.array(['a','b','c','d'])
s=pd.Series(data,index)
s

In [28]:
import pandas as pd
import numpy as np
data=np.array(['a','b','c','d'])
s=pd.Series(data)
s

0    a
1    b
2    c
3    d
dtype: object

In [29]:
s=pd.Series(5,index=[0,1,2,3])
s


0    5
1    5
2    5
3    5
dtype: int64

In [30]:
s=pd.Series(data,index=[100,101,102,103])
s


100    a
101    b
102    c
103    d
dtype: object

In [31]:
data=[['Alex',10],['bob',12],['jim',13]]
df=pd.DataFrame(data,columns=['Name','Age'])
df

Name  Age
0  Alex   10
1   bob   12
2   jim   13

In [32]:
data={'Name':['tom','jack','steve','ricky'],
     'age':[28,27,26,25]}
df=pd.DataFrame(data)
df


Name  age
0    tom   28
1   jack   27
2  steve   26
3  ricky   25

In [33]:
data={'Name':pd.Series(['tom','james','ricky','steve']),
     'Age':pd.Series([25,26,27,28]),
     'Rating':pd.Series([4.23,3.2,2.5,4.6])}
df=pd.DataFrame(data)
df

Name  Age  Rating
0    tom   25    4.23
1  james   26    3.20
2  ricky   27    2.50
3  steve   28    4.60

In [34]:
df.T

0      1      2      3
Name     tom  james  ricky  steve
Age       25     26     27     28
Rating  4.23    3.2    2.5    4.6

In [35]:
df.ndim

2

In [36]:
df.shape

(4, 3)

In [37]:
df.size

12

In [38]:
df.head(2)

Name  Age  Rating
0    tom   25    4.23
1  james   26    3.20

In [39]:
df.tail(2)

Name  Age  Rating
2  ricky   27     2.5
3  steve   28     4.6

In [40]:
df.values

array([['tom', 25, 4.23],
       ['james', 26, 3.2],
       ['ricky', 27, 2.5],
       ['steve', 28, 4.6]], dtype=object)

In [41]:
df.mean()

Age       26.5000
Rating     3.6325
dtype: float64

In [42]:
df.median()

Age       26.500
Rating     3.715
dtype: float64

In [43]:
df.std()

Age       1.290994
Rating    0.959631
dtype: float64

In [44]:
df.max()

Name      tom
Age        28
Rating    4.6
dtype: object

In [45]:
df.min()

Name      james
Age          25
Rating      2.5
dtype: object

In [46]:
df.describe()

Age    Rating
count   4.000000  4.000000
mean   26.500000  3.632500
std     1.290994  0.959631
min    25.000000  2.500000
25%    25.750000  3.025000
50%    26.500000  3.715000
75%    27.250000  4.322500
max    28.000000  4.600000

In [47]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
Name      4 non-null object
Age       4 non-null int64
Rating    4 non-null float64
dtypes: float64(1), int64(1), object(1)
memory usage: 224.0+ bytes


In [1]:
import pandas as pd
import numpy as np
df=pd.DataFrame(np.random.randn(10,2),
               index=[1,4,6,2,3,5,9,8,0,7],
               columns=['col2','col1'])
df

col2      col1
1  1.483684 -0.853027
4 -0.691826 -0.468205
6 -1.274200 -1.494159
2 -0.086403 -0.435322
3 -0.298742 -0.612174
5  0.203697  0.423847
9 -0.004708  1.163319
8 -1.588682 -0.450272
0  0.880105  0.611148
7  0.618061  2.516390

In [2]:
df.sort_index()

col2      col1
0  0.880105  0.611148
1  1.483684 -0.853027
2 -0.086403 -0.435322
3 -0.298742 -0.612174
4 -0.691826 -0.468205
5  0.203697  0.423847
6 -1.274200 -1.494159
7  0.618061  2.516390
8 -1.588682 -0.450272
9 -0.004708  1.163319

In [4]:
df=pd.DataFrame({'col1':[2,1,1,1],
                'col2':[1,3,2,4]})
df

col1  col2
0     2     1
1     1     3
2     1     2
3     1     4

In [5]:
df.sort_values(by='col1')

col1  col2
1     1     3
2     1     2
3     1     4
0     2     1

In [6]:
df.sort_values(by='col2')

col1  col2
0     2     1
2     1     2
1     1     3
3     1     4

In [7]:
df=pd.DataFrame(np.random.randn(8,4),
               index=['a','b','c','d','e','f','g','h'],
               columns=['A','B','C','D'])
df

A         B         C         D
a  0.568769  1.201582 -1.741540  0.580530
b  0.584336  0.538849  0.484724 -1.085101
c -1.875493  0.198209  0.926233 -1.206670
d -0.079228  0.009203 -1.062875  0.802462
e  0.289860  0.588281  0.122282  0.255552
f -1.651241  0.558716  0.282304 -0.563853
g -0.731893 -0.613312  1.813066 -0.116675
h  0.269815 -1.000951 -0.630456  0.184871

In [8]:
df.loc[:,'A']

a    0.568769
b    0.584336
c   -1.875493
d   -0.079228
e    0.289860
f   -1.651241
g   -0.731893
h    0.269815
Name: A, dtype: float64

In [9]:
df.loc[:,['A','B']]

A         B
a  0.568769  1.201582
b  0.584336  0.538849
c -1.875493  0.198209
d -0.079228  0.009203
e  0.289860  0.588281
f -1.651241  0.558716
g -0.731893 -0.613312
h  0.269815 -1.000951

In [10]:
df.loc[['a','b','f','h'],['A','C']]

A         C
a  0.568769 -1.741540
b  0.584336  0.484724
f -1.651241  0.282304
h  0.269815 -0.630456

In [11]:
df.A

a    0.568769
b    0.584336
c   -1.875493
d   -0.079228
e    0.289860
f   -1.651241
g   -0.731893
h    0.269815
Name: A, dtype: float64

In [12]:
df

A         B         C         D
a  0.568769  1.201582 -1.741540  0.580530
b  0.584336  0.538849  0.484724 -1.085101
c -1.875493  0.198209  0.926233 -1.206670
d -0.079228  0.009203 -1.062875  0.802462
e  0.289860  0.588281  0.122282  0.255552
f -1.651241  0.558716  0.282304 -0.563853
g -0.731893 -0.613312  1.813066 -0.116675
h  0.269815 -1.000951 -0.630456  0.184871

In [13]:
df.iloc[:4]

A         B         C         D
a  0.568769  1.201582 -1.741540  0.580530
b  0.584336  0.538849  0.484724 -1.085101
c -1.875493  0.198209  0.926233 -1.206670
d -0.079228  0.009203 -1.062875  0.802462

In [14]:
df.iloc[1:5,2:4]

C         D
b  0.484724 -1.085101
c  0.926233 -1.206670
d -1.062875  0.802462
e  0.122282  0.255552

In [15]:
df.iloc[1:3,:]

A         B         C         D
b  0.584336  0.538849  0.484724 -1.085101
c -1.875493  0.198209  0.926233 -1.206670

In [16]:
df.iloc[:,1:3]

B         C
a  1.201582 -1.741540
b  0.538849  0.484724
c  0.198209  0.926233
d  0.009203 -1.062875
e  0.588281  0.122282
f  0.558716  0.282304
g -0.613312  1.813066
h -1.000951 -0.630456

In [17]:
df=pd.DataFrame(np.random.randn(5,3),
               index=['a','c','e','f','h'],
               columns=['one','two','three'])
df

one       two     three
a  0.019886 -0.263194  1.732721
c -0.008993 -1.507868 -0.849132
e -0.351320 -1.294850  1.168158
f -0.362210  0.797349  1.617501
h -0.432750  0.183164 -1.299686

In [18]:
df.reindex(['a','b','c','d','e','f','g','h'])

one       two     three
a  0.019886 -0.263194  1.732721
b       NaN       NaN       NaN
c -0.008993 -1.507868 -0.849132
d       NaN       NaN       NaN
e -0.351320 -1.294850  1.168158
f -0.362210  0.797349  1.617501
g       NaN       NaN       NaN
h -0.432750  0.183164 -1.299686

In [19]:
df['one'].isnull()

a    False
c    False
e    False
f    False
h    False
Name: one, dtype: bool

In [20]:
df['one'].notnull()

a    True
c    True
e    True
f    True
h    True
Name: one, dtype: bool

In [21]:
df.fillna(0)

one       two     three
a  0.019886 -0.263194  1.732721
c -0.008993 -1.507868 -0.849132
e -0.351320 -1.294850  1.168158
f -0.362210  0.797349  1.617501
h -0.432750  0.183164 -1.299686

In [22]:
df

one       two     three
a  0.019886 -0.263194  1.732721
c -0.008993 -1.507868 -0.849132
e -0.351320 -1.294850  1.168158
f -0.362210  0.797349  1.617501
h -0.432750  0.183164 -1.299686

In [23]:
df=pd.DataFrame(np.random.randn(5,3),
               index=['a','c','e','f','h'],
               columns=['one','two','three'])
df

one       two     three
a  0.062143 -2.299279  0.347013
c  0.207790  0.278260  1.091139
e  0.445007  0.273621  0.597909
f  0.421992  0.861205  0.288232
h  0.142971  1.293936 -0.743482

In [24]:
df.reindex(['a','b','c','d','e','f','g','h'])

one       two     three
a  0.062143 -2.299279  0.347013
b       NaN       NaN       NaN
c  0.207790  0.278260  1.091139
d       NaN       NaN       NaN
e  0.445007  0.273621  0.597909
f  0.421992  0.861205  0.288232
g       NaN       NaN       NaN
h  0.142971  1.293936 -0.743482

In [25]:
df.fillna(0)

one       two     three
a  0.062143 -2.299279  0.347013
c  0.207790  0.278260  1.091139
e  0.445007  0.273621  0.597909
f  0.421992  0.861205  0.288232
h  0.142971  1.293936 -0.743482